groups:
 - name: "1.1"
   channels:
    - name: alpha
      version: 1.1.23+fix50
    - name: beta
      version: 1.1.23+fix25
    - name: ea
      version: 1.1.22+fix40
    - name: stable
      version: 1.1.21+fix40
    - name: rock-solid
      version: 1.1.21
 - name: "1.2"
   channels:
    - name: alpha
      version: 1.2.34 # Feature X was implemented
    - name: beta
      version: 1.2.33 # Feature Y was implemented
    - name: ea
      version: 1.2.27+fix3
