groups:
 - name: "v1"
   channels:
    - name: alpha
      version: 1.2.23+fix50
    - name: beta
      version: 1.2.23+fix25
    - name: ea
      version: 1.1.22+fix40
    - name: stable
      version: 1.1.21+fix40
    - name: rock-solid
      version: 1.1.21
 - name: "v2"
   channels:
    - name: alpha
      version: 2.3.0-alpha.3
    - name: beta
      version: 1.2.4
    - name: ea
      version: 2.2.3
